apiVersion: v1
kind: Secret
metadata:
    name: proxmox-credentials
type: Opaque
data:
    token_secret: ENC[AES256_GCM,data:L4JkOjnwuSyuvcJY2BVLaIq7pQ1/HGpU99iCHpM53wU1fh9M,iv:UHK2Ut/amckbcWIiylPifHTACO6MWk0384e6Yopn6vU=,tag:J/Bvz+0bAQ30VgibBQcW1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19q4q30qezma5jmfl5s2hv7xgws8z6030wlvj8mc6xjaenay2c48s42epnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5alExQUlVbDBhaWIzbW5r
            OXpvTTlYcC8zQ3RSaFBheitXaTM0cDJRMnkwCng0Y2h0WFBEU2lWaG5uOUVBSnJp
            TUFlMFF3aUNPMUQvTU1veVZFcGRvNTAKLS0tIHhmcDJiNzBkVVhnbTBBdVV2V21C
            a3J6UHR6ZStadEVGWERmd2xQZDhMUmsKI7atk8PbvAC/4jLdcAprjmdJXR56HWED
            VdbyPwo4Je2AOE2RZMhtE31XF+OHKs9ZNk1pZiuGtaStSqrZbTifxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T11:28:07Z"
    mac: ENC[AES256_GCM,data:DnUD5BExzFgGsVdLW23e0fGIY9PsRHB6JHaVLrNl2y4RVA0XLcMe1mq4BXMS2/qK4doNVIKby72dV/YQawHu632AkGjc3CJVYODbBPU6cQmjnMrx5eOavyP01Ir7Ix0NRWr355R7b9jUlwRtb3jrCjwazwzVas1rZ0++BilL4IM=,iv:g+BGaiGEau8dIoY4690JTISJmPTlmeU0YMgtTK+3OYc=,tag:qbPRkx0ae36BRrA+tmOFuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3