apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# baselines
- ../../baseline/cilium
- ../../baseline/csi-proxmox
- ../../baseline/metallb
- ../../baseline/traefik
- ../../baseline/cert-manager
# todo: overlays