---
apiVersion: v1
kind: Namespace
metadata:
  name: app-authelia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data-dir
  namespace: app-authelia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: proxmox-data-xfs
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authelia
  namespace: app-authelia
spec:
  interval: 1h
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: app-authelia
spec:
  interval: 30m
  chart:
    spec:
      chart: authelia
      version: "0.8.58"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: app-authelia
      interval: 1h
  values:
    domain: stage.familie-siebert.de
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-familie-siebert-de
      certManager: true
      rewriteTarget: true
      subdomain: auth
      tls:
        enabled: true
        secret: authelia-general-tls
    configmap:
      authentication_backend:
        ldap:
          enabled: false
        file:
          enabled: false
      storage:
        local:
          enabled: false
          path: /config/db.sqlite3
        mysql:
          enabled: false
        postgres:
          enabled: false
      session:
        redis:
          enabled: false
      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt
      identity_providers:
        oidc:
          enabled: true
    persistence:
      enabled: true
      storageClass: proxmox-data-xfs

