---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  addresses:
  - 192.168.1.221/32
  - 192.168.1.222/32
  - 192.168.1.223/32
  - 192.168.1.224/32
  - 192.168.1.225/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  ipAddressPools:
  - metallb