---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-metallb
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  interval: 1h
  url:  https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.13.12"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: infra-metallb
      interval: 1h
---
#apiVersion: metallb.io/v1beta1
#kind: IPAddressPool
#metadata:
#  name: metallb
#  namespace: infra-metallb
#spec:
#  addresses:
#  - 192.168.1.221/32
#  - 192.168.1.222/32
#  - 192.168.1.223/32
#---
#apiVersion: metallb.io/v1beta1
#kind: L2Advertisement
#metadata:
#  name: metallb
#  namespace: infra-metallb
#spec:
#  ipAddressPools:
#  - metallb