---
apiVersion: v1
kind: Namespace
metadata:
  name: app-netdata
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: netdata
  namespace: app-netdata
spec:
  interval: 1h
  url: https://netdata.github.io/helmchart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: app-netdata
spec:
  interval: 30m
  chart:
    spec:
      chart: netdata
      version: "3.7.80"
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: app-netdata
      interval: 1h
  values:
    ingress:
      enabled: true
      hosts: netdata.stage.familie-siebert.de
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-familie-siebert-de
      spec:
        tls:
        - secretName: netdata-general-tls
          hosts:
          - netdata.stage.familie-siebert.de
    k8sState:
      persistence:
        storageclass: proxmox-data-xfs